### ISSUE TITLE
plugin setting for language does not seem to force the language

### ISSUE THREAD

**Issue by WebDevJona** [evoWeb/recaptcha#10]
Hi,

very much like your extension.

in our setup we need to distinguish different language locales (e.g. germany, switzerland, austria) but setting the plugin setting
`plugin.tx_recaptcha.lang = de`
depending on the current selected language does not seem to change the resulting recaptch code. Maybe I'm just missing something but I didn't found the right entry point in the extension, otherwise this may be a pull request. :)

Looking forward to any feedback.

kind regards
jonathan

**Comment by garbast** [comment]
In general reCAPTCHA detects the browser language and displays accordingly. So i would suggest to keep the autodetection on.

If for what ever weird reason the customer is not satisfied with that you could add the different language keys by changing

plugin.tx_recaptcha.public_key.wrap = <div class="g-recaptcha" data-sitekey="|" data-language="de"></div>

Due to missleading expectations i think about getting rid of the lang setting.

**Comment by WebDevJona** [comment]
Hi,

thanks for the quick reply. Regarding the differenct german versions the browser detection is suffictient.

The feedback of our customer is, when switching to spain the content changes but the captcha does not.

I'll look into it with different keys. Thanks again!

Jonathan
