### ISSUE TITLE
include_invisible_recaptcha_callback is not working

### ISSUE THREAD

**Issue by dogawaf** [evoWeb/recaptcha#4]
Hello

I am not able to get include_invisible_recaptcha_callback working. The inlineJs is not inserted on the page.
According to the TYPO3 CMS source code (`\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGet`), page.jsInline should be a numerical array. Any non-numerical key are stripped away.

Cheers

TYPO3 8.7

**Comment by garbast** [comment]
Changed in the develop branch. Please check if this solves your problem and report back. If its working i will tag a new version.

**Comment by dahaupt** [comment]
@garbast On my 32bit environment of PHP (XAMPP) it is not working with `1508480348393` as numerical key.

If I use `10` as numerical key it's working and generated. So probably this works on server environments.

**Comment by evoWeb** [comment]
1508480348393 is to large for 32bit systems.

As i'm not able to predict which numerical keys are already taken i need to make sure that the extension does not override previous configured javascript. That's why i choose the timestamp of the first time i created the condition. This should reduce the possiblie collisions.

From my point of view 32bit systems are dead. To everyone that is still working with 32bit versions of xampp my advice is to switch to 64bit. I wont fix any issue related to 32bit problems.

**Comment by dahaupt** [comment]
@evoWeb I agree, but currently there is no 64bit version of xampp available for windows. 

I should switch to linux or mac os 😆
