### ISSUE TITLE
Default TS public_key overwrites EXT config

### ISSUE THREAD

**Issue by hoermannklaus** [evoWeb/recaptcha#42]
I have an issue with the settings of the "public_key" and "private_key".

I use envvars in a Docker Container which again get set to the EXT config settings in the "LocalConfiguration.php". This works fine. I read in the documentation, that the EXT config gets overwritten with the TS template settings.

The TS template has default settings, which then overwrite my EXT config settings. 

In order for me to work, I had to set the "public_key" and "private_key" in the TS constants to "" (empty) in order not to overwrite my EXT conf settings. 

I did not expect that the "default" values overwrite my EXT config settings, which in my believe should be of higher priority.

**Comment by garbast** [comment]
Default behaviour is that the constants (via setup) gets used if the settings are present. If you do not use the include static ts because you have different usage, this is no problem. But the common user does not use docker with env settings and need help to not get lost with a not so sane configuration.

With less experience user in mind i wont change the configuration handling for now. If you think you have a better solution, for the configuration merging, you can hand in a pull request.

**Comment by hoermannklaus** [comment]
Thanks for the quick reply.
